deployBackend:
  script:
  - cp -r src/* /srv/http/sonne
  - cd /srv/http/sonne
  - sudo systemctl stop daphne
  - pip install --user -r requirements.txt
  - python manage.py migrate
  - python manage.py collectstatic --no-input
  - sudo systemctl start daphne
  only:
  - backend
  tags:
  - sonne2
  when: manual
  environment:
    name: django2
    url: https://sonne.0ds.de
