deployBackend:
  script:
  - cp -r * /srv/http/sonne
  - cd /srv/http/sonne
  - pip install --user -r requirements.txt
  - python manage.py
  - sudo systemctl restart daphne
  only:
  - backend
  tags:
  - sonne
  when: manual
  environment:
    name: django
    url: https://sonne.0ds.de
