# Generated by Django 2.1.6 on 2019-04-06 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    replaces = [('solr_channel', '0001_initial'), ('solr_channel', '0002_auto_20190406_0928')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph_str', models.TextField()),
                ('ctime', models.DateTimeField(verbose_name='creation time')),
                ('mtime', models.DateTimeField(verbose_name='modification time')),
            ],
        ),
    ]
